name: madcamp_week2_test
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  http: ^1.2.2
  qr_flutter: ^4.1.0
  qr_code_scanner: 1.0.1
  flutter_native_splash: ^2.4.4

  # 소셜 로그인: 구글, 카카오
  google_sign_in: ^6.2.2
  kakao_flutter_sdk: ^1.9.6 # 전체 추가
  kakao_flutter_sdk_user: ^1.9.5 # 카카오 로그인 API 패키지

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Thin.otf
          weight: 100
        - asset: fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: fonts/Pretendard-Light.otf
          weight: 300
        - asset: fonts/Pretendard-Regular.otf
          weight: 400
        - asset: fonts/Pretendard-Medium.otf
          weight: 500
        - asset: fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: fonts/Pretendard-Bold.otf
          weight: 700
        - asset: fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: fonts/Pretendard-Black.otf
          weight: 900

flutter_native_splash:
  color: "#0FD380" # 배경색
  image: assets/splash.png # 스플래쉬 화면에 표시할 이미지
  android: true
  ios: true
